### ISSUE TITLE
Allow use without creating MFA device

### ISSUE THREAD

**Issue by chrisgilmerproj** [trussworks/setup-new-aws-user#52]
I've found it very useful in previous iterations of this script on my project to allow a user to reset their credentials without also managing the MFA (because they already have one set up). In my case the script would read from the env var `NO_MFA` and if `NO_MFA=1` was set then it would skip all MFA functions. It would be nice to have a flag for this command called `--no-mfa` that also disabled the MFA functions in a similar way.

**Comment by dynamike** [comment]
Totally makes sense, can you pop it as a story in the infrasec-reserve icebox?

**Comment by chrisgilmerproj** [comment]
> Totally makes sense, can you pop it as a story in the infrasec-reserve icebox?

I may end up needing this for myself so if I don't tackle it then yes I'll throw it in the icebox.

**Comment by chrisgilmerproj** [comment]
Closed by https://github.com/trussworks/setup-new-aws-user/pull/68
